# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rest_pb2 as rest__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RestaurantServiceStub(object):
    """Restaurant ordering service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.login = channel.unary_unary(
                '/restaurant.RestaurantService/login',
                request_serializer=rest__pb2.LoginRequest.SerializeToString,
                response_deserializer=rest__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.logout = channel.unary_unary(
                '/restaurant.RestaurantService/logout',
                request_serializer=rest__pb2.LogoutRequest.SerializeToString,
                response_deserializer=rest__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.get_menu = channel.unary_unary(
                '/restaurant.RestaurantService/get_menu',
                request_serializer=rest__pb2.MenuRequest.SerializeToString,
                response_deserializer=rest__pb2.MenuResponse.FromString,
                _registered_method=True)
        self.update_menu_price = channel.unary_unary(
                '/restaurant.RestaurantService/update_menu_price',
                request_serializer=rest__pb2.UpdateMenuPriceRequest.SerializeToString,
                response_deserializer=rest__pb2.UpdateMenuPriceResponse.FromString,
                _registered_method=True)
        self.place_dine_in_order = channel.unary_unary(
                '/restaurant.RestaurantService/place_dine_in_order',
                request_serializer=rest__pb2.DineInOrderRequest.SerializeToString,
                response_deserializer=rest__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.place_takeout_order = channel.unary_unary(
                '/restaurant.RestaurantService/place_takeout_order',
                request_serializer=rest__pb2.TakeoutOrderRequest.SerializeToString,
                response_deserializer=rest__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.list_orders = channel.unary_unary(
                '/restaurant.RestaurantService/list_orders',
                request_serializer=rest__pb2.ListOrdersRequest.SerializeToString,
                response_deserializer=rest__pb2.ListOrdersResponse.FromString,
                _registered_method=True)
        self.mark_order_ready = channel.unary_unary(
                '/restaurant.RestaurantService/mark_order_ready',
                request_serializer=rest__pb2.MarkOrderReadyRequest.SerializeToString,
                response_deserializer=rest__pb2.MarkOrderReadyResponse.FromString,
                _registered_method=True)


class RestaurantServiceServicer(object):
    """Restaurant ordering service.
    """

    def login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_menu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_menu_price(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def place_dine_in_order(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def place_takeout_order(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list_orders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mark_order_ready(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaurantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=rest__pb2.LoginRequest.FromString,
                    response_serializer=rest__pb2.LoginResponse.SerializeToString,
            ),
            'logout': grpc.unary_unary_rpc_method_handler(
                    servicer.logout,
                    request_deserializer=rest__pb2.LogoutRequest.FromString,
                    response_serializer=rest__pb2.LogoutResponse.SerializeToString,
            ),
            'get_menu': grpc.unary_unary_rpc_method_handler(
                    servicer.get_menu,
                    request_deserializer=rest__pb2.MenuRequest.FromString,
                    response_serializer=rest__pb2.MenuResponse.SerializeToString,
            ),
            'update_menu_price': grpc.unary_unary_rpc_method_handler(
                    servicer.update_menu_price,
                    request_deserializer=rest__pb2.UpdateMenuPriceRequest.FromString,
                    response_serializer=rest__pb2.UpdateMenuPriceResponse.SerializeToString,
            ),
            'place_dine_in_order': grpc.unary_unary_rpc_method_handler(
                    servicer.place_dine_in_order,
                    request_deserializer=rest__pb2.DineInOrderRequest.FromString,
                    response_serializer=rest__pb2.OrderResponse.SerializeToString,
            ),
            'place_takeout_order': grpc.unary_unary_rpc_method_handler(
                    servicer.place_takeout_order,
                    request_deserializer=rest__pb2.TakeoutOrderRequest.FromString,
                    response_serializer=rest__pb2.OrderResponse.SerializeToString,
            ),
            'list_orders': grpc.unary_unary_rpc_method_handler(
                    servicer.list_orders,
                    request_deserializer=rest__pb2.ListOrdersRequest.FromString,
                    response_serializer=rest__pb2.ListOrdersResponse.SerializeToString,
            ),
            'mark_order_ready': grpc.unary_unary_rpc_method_handler(
                    servicer.mark_order_ready,
                    request_deserializer=rest__pb2.MarkOrderReadyRequest.FromString,
                    response_serializer=rest__pb2.MarkOrderReadyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'restaurant.RestaurantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('restaurant.RestaurantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RestaurantService(object):
    """Restaurant ordering service.
    """

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/login',
            rest__pb2.LoginRequest.SerializeToString,
            rest__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/logout',
            rest__pb2.LogoutRequest.SerializeToString,
            rest__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_menu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/get_menu',
            rest__pb2.MenuRequest.SerializeToString,
            rest__pb2.MenuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_menu_price(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/update_menu_price',
            rest__pb2.UpdateMenuPriceRequest.SerializeToString,
            rest__pb2.UpdateMenuPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def place_dine_in_order(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/place_dine_in_order',
            rest__pb2.DineInOrderRequest.SerializeToString,
            rest__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def place_takeout_order(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/place_takeout_order',
            rest__pb2.TakeoutOrderRequest.SerializeToString,
            rest__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def list_orders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/list_orders',
            rest__pb2.ListOrdersRequest.SerializeToString,
            rest__pb2.ListOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def mark_order_ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/restaurant.RestaurantService/mark_order_ready',
            rest__pb2.MarkOrderReadyRequest.SerializeToString,
            rest__pb2.MarkOrderReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
